version: '3.8'
services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - yuuyu-network
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/mnt/VG1/LV1/nextcloud
      # - NEXTCLOUD_MOUNT=/mnt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`cloud.yuuyu.dev`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.portainer.service=portainer-service"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=11000"
      # - "traefik.http.services.portainer-service.loadbalancer.server.scheme=https"
    restart: always
networks:
  yuuyu-network:
    external: true
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
